name: .NET CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore WebApplication1.sln

      - name: Build WebApplication1
        run: dotnet build --configuration Release --no-restore WebApplication1/WebApplication1.csproj

      - name: Build TestProject1
        run: dotnet build --configuration Release --no-restore TestProject1/TestProject1.csproj

      - name: Run Tests
        run: dotnet test --configuration Release --no-restore --verbosity normal TestProject1/TestProject1.csproj

      - name: Publish WebApplication1
        run: dotnet publish -c Release -o ./publish WebApplication1/WebApplication1.csproj

      - name: Upload Published Web Application
        uses: actions/upload-artifact@v4
        with:
          name: published-webapp
          path: ./publish
